export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_MEALS = "FETCH_MEALS";
export const FETCH_MEAL_DETAIL = "FETCH_MEAL_DETAIL";
